/*************************************/
-- SAP HANA Graph examples - Topological Sort
-- 2020-10-01
-- This script was developed for SAP HANA Cloud 2020 Q2
-- Wikipedia https://en.wikipedia.org/wiki/Topological_sorting
/*************************************/

/*************************************/
-- 1 Create schema, tables, graph workspace, and load some sample data
DROP SCHEMA "GRAPHSCRIPT" CASCADE;
CREATE SCHEMA "GRAPHSCRIPT";
CREATE COLUMN TABLE "GRAPHSCRIPT"."VERTICES" (
    "ID" BIGINT PRIMARY KEY,
    "NAME" NVARCHAR(5000),
    "ORDER"	BIGINT DEFAULT NULL
);
CREATE COLUMN TABLE "GRAPHSCRIPT"."EDGES" (
    "ID" BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    "SOURCE" BIGINT NOT NULL REFERENCES "GRAPHSCRIPT"."VERTICES" ("ID") ON UPDATE CASCADE ON DELETE CASCADE,
    "TARGET" BIGINT NOT NULL REFERENCES "GRAPHSCRIPT"."VERTICES" ("ID") ON UPDATE CASCADE ON DELETE CASCADE,
    "WEIGHT" DOUBLE
);
INSERT INTO "GRAPHSCRIPT"."VERTICES" ("ID") VALUES (1);
INSERT INTO "GRAPHSCRIPT"."VERTICES" ("ID") VALUES (2);
INSERT INTO "GRAPHSCRIPT"."VERTICES" ("ID") VALUES (3);
INSERT INTO "GRAPHSCRIPT"."VERTICES" ("ID") VALUES (4);
INSERT INTO "GRAPHSCRIPT"."VERTICES" ("ID") VALUES (5);
INSERT INTO "GRAPHSCRIPT"."VERTICES" ("ID") VALUES (20);
INSERT INTO "GRAPHSCRIPT"."VERTICES" ("ID") VALUES (30);
INSERT INTO "GRAPHSCRIPT"."VERTICES" ("ID") VALUES (40);
INSERT INTO "GRAPHSCRIPT"."VERTICES" ("ID") VALUES (300);
INSERT INTO "GRAPHSCRIPT"."VERTICES" ("ID") VALUES (400);
INSERT INTO "GRAPHSCRIPT"."EDGES" ("SOURCE", "TARGET", "WEIGHT") VALUES (1, 2, 0.0);
INSERT INTO "GRAPHSCRIPT"."EDGES" ("SOURCE", "TARGET", "WEIGHT") VALUES (1, 3, 0.0);
INSERT INTO "GRAPHSCRIPT"."EDGES" ("SOURCE", "TARGET", "WEIGHT") VALUES (3, 4, 0.0);
INSERT INTO "GRAPHSCRIPT"."EDGES" ("SOURCE", "TARGET", "WEIGHT") VALUES (4, 5, 0.0);
INSERT INTO "GRAPHSCRIPT"."EDGES" ("SOURCE", "TARGET", "WEIGHT") VALUES (3, 20, 0.0);
INSERT INTO "GRAPHSCRIPT"."EDGES" ("SOURCE", "TARGET", "WEIGHT") VALUES (20, 30, 0.0);
INSERT INTO "GRAPHSCRIPT"."EDGES" ("SOURCE", "TARGET", "WEIGHT") VALUES (30, 40, 0.0);
INSERT INTO "GRAPHSCRIPT"."EDGES" ("SOURCE", "TARGET", "WEIGHT") VALUES (3, 300, 0.0);
INSERT INTO "GRAPHSCRIPT"."EDGES" ("SOURCE", "TARGET", "WEIGHT") VALUES (300, 400, 0.0);
INSERT INTO "GRAPHSCRIPT"."EDGES" ("SOURCE", "TARGET", "WEIGHT") VALUES (300, 2, 0.0);
INSERT INTO "GRAPHSCRIPT"."EDGES" ("SOURCE", "TARGET", "WEIGHT") VALUES (4, 20, 0.0);

/****************************************************/
-- create workspace
CREATE GRAPH WORKSPACE "GRAPHSCRIPT"."GRAPHWS"
	EDGE TABLE "GRAPHSCRIPT"."EDGES"
		SOURCE COLUMN "SOURCE"
		TARGET COLUMN "TARGET"
		KEY COLUMN "ID"
	VERTEX TABLE "GRAPHSCRIPT"."VERTICES"
		KEY COLUMN "ID";


/****************************************************/
-- procedure Topologial Sort
CREATE TYPE "GRAPHSCRIPT"."TT_VERTICES" AS TABLE ("ID" BIGINT, "REV_ORDER" BIGINT);

CREATE OR REPLACE PROCEDURE "GRAPHSCRIPT"."GS_TOPOLOGICAL_SORT" (
		OUT o_res "GRAPHSCRIPT"."TT_VERTICES"
	)
	LANGUAGE GRAPH READS SQL DATA AS
BEGIN
	GRAPH g = Graph("GRAPHSCRIPT", "GRAPHWS");
	ALTER g ADD TEMPORARY VERTEX ATTRIBUTE (BIGINT "REV_ORDER" = 0L);

	BIGINT c_exitOrder = 1L;
	FOREACH v_start IN Vertices(:g) {
		IF (:v_start."REV_ORDER" == 0L) {
			TRAVERSE DFS :g FROM :v_start ON EXIT VERTEX (Vertex v) {
				v."REV_ORDER" = :c_exitOrder;
				c_exitOrder = :c_exitOrder + 1L;
	        };
		}
	}
	o_res = SELECT :v."ID", :v."REV_ORDER" FOREACH v IN Vertices(:g);
END;
CALL "GRAPHSCRIPT"."GS_TOPOLOGICAL_SORT"(?);

-- Optional: wrap the procedure in a function
CREATE OR REPLACE FUNCTION "GRAPHSCRIPT"."F_TOPOLOGICAL_SORT" ()
    RETURNS "GRAPHSCRIPT"."TT_VERTICES"
LANGUAGE SQLSCRIPT READS SQL DATA AS
BEGIN
    CALL "GRAPHSCRIPT"."GS_TOPOLOGICAL_SORT"(o_res);
    RETURN :o_res;
END;

SELECT * FROM "GRAPHSCRIPT"."F_TOPOLOGICAL_SORT"() ORDER BY "REV_ORDER" DESC;
